/* Test-only redesign layered over the full current application. */
(()=>{'use strict';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[['dashboard','⌂','Dashboard'],['preconstruction','✓','Preconstruction'],['pos','$','Purchase Orders'],['selections','◇','Final Selections'],['schedule','▦','Schedule'],['estimate','▤','Estimate'],['costing','▥','Job Costing'],['files','▱','Files']];
let calendarExpanded=true;let scheduleView='month',calendarMessage='';let compareInitialized=false;let active='dashboard',costMode='job',team='all',month=new Date(new Date().getFullYear(),new Date().getMonth(),1);const chosen=new Set();
const toolbar=document.createElement('nav');toolbar.id='redesignNav';toolbar.setAttribute('aria-label','Main sections');document.querySelector('.operations-header').after(toolbar);
const subtitle=document.querySelector('.operations-header .brand small');if(subtitle)subtitle.textContent='Operations Workspace';
for(const id of ['redesign-costing','redesign-schedule']){const section=document.createElement('section');section.id=id;section.className='page';document.querySelector('main.content').append(section)}
const account=document.querySelector('.sidebar-account-wrap');const themes=document.createElement('div');themes.className='redesign-themes';themes.innerHTML='<button onclick="JJRedesign.theme(\'current\')">☀ Day</button><button onclick="JJRedesign.theme(\'night\')">☾ Night</button>';account.before(themes);
const collapse=document.createElement('button');collapse.id='redesignSidebarToggle';collapse.setAttribute('aria-label','Collapse jobs sidebar');collapse.onclick=()=>{const mobile=matchMedia('(max-width:900px)').matches;document.body.classList.toggle(mobile?'redesign-sidebar-open':'redesign-sidebar-collapsed');collapse.setAttribute('aria-expanded',String(mobile?document.body.classList.contains('redesign-sidebar-open'):!document.body.classList.contains('redesign-sidebar-collapsed')))};collapse.innerHTML='‹';document.body.append(collapse);
function theme(value){document.documentElement.dataset.previewTheme=value==='night'?'night':'current';try{localStorage.setItem('jj_test_design_theme',value)}catch{}themes.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String((i===1)===(value==='night'))))}
const iconPaths={dashboard:'M3 11 12 3l9 8M5 10v11h14V10M9 21v-7h6v7',preconstruction:'m5 12 4 4L19 6',estimate:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5',selections:'m12 3 9 9-9 9-9-9z',schedule:'M4 5h16v16H4zM4 10h16M8 3v4M16 3v4',pos:'M12 2v20M18 6H9a4 4 0 0 0 0 8h6a4 4 0 0 0 0-8',costing:'M4 20V12h4v8M10 20V7h4v13M16 20V3h4v17',files:'M3 6h7l2 3h9v11H3z'};
const chrome=document.createElement('div');chrome.id='redesignChrome';const header=document.querySelector('.operations-header');header.before(chrome);chrome.append(header,toolbar);
function syncNav(){toolbar.innerHTML=routes.map(([id,icon,label])=>`<button aria-current="${active===id?'page':'false'}" onclick="JJRedesign.navigate('${id}')"><svg class="rd-nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[id]}"></path></svg>${label}</button>`).join('');const p=selectedProject();let name=document.getElementById('redesignJobName');if(!name){name=document.createElement('div');name.id='redesignJobName';chrome.after(name)}name.textContent=p?`${p.name} · ${p.jobNo||''}`:'Choose a job';document.querySelectorAll('.project-side-wrap').forEach(el=>el.setAttribute('aria-current',el.classList.contains('active')?'true':'false'))}
let scrollResetToken=0;
function sectionTop(){const token=++scrollResetToken;const reset=()=>{if(token!==scrollResetToken)return;for(const el of [document.scrollingElement,document.documentElement,document.body,document.querySelector('.operations-main'),document.querySelector('main.content')]){if(el){el.scrollTop=0;el.scrollLeft=0;}}window.scrollTo({top:0,left:0,behavior:'instant'});};reset();requestAnimationFrame(()=>requestAnimationFrame(reset));}
if(window.history&&'scrollRestoration' in window.history)window.history.scrollRestoration='manual';
window.addEventListener('pageshow',()=>sectionTop());
window.addEventListener('load',()=>sectionTop());
const originalGo=go;go=function(id){if(!document.getElementById(id))return;const before=document.querySelector('.page.active')?.id;originalGo(id);const map={dashboard:'dashboard',preconstruction:'preconstruction',selections:'selections',paybyline:poHubView==='estimate'?'estimate':'pos',estimates:'estimate',project:projectTab==='jobcost'?'costing':projectTab==='files'?'files':active,'jj-workpay':'pos','redesign-costing':'costing','redesign-schedule':'schedule'};active=map[id]||active;syncNav();if(before!==id)sectionTop()};
async function navigate(id){if(window.JJTestWorkPay?.flushEdits&&!await JJTestWorkPay.flushEdits())return;const changed=active!==id;active=id;if(changed)sectionTop();if(id==='dashboard'){renderDashboard();go('dashboard')}else if(id==='preconstruction'){renderPreconstruction();go('preconstruction')}else if(id==='selections'){renderSelections();go('selections')}else if(id==='estimate'||id==='pos'){openProjectPOHub(selectedProject().id,id==='estimate'?'estimate':'splits')}else if(id==='files'){projectTab='files';renderProject();go('project')}else if(id==='costing'){go('redesign-costing');await renderCosts()}else if(id==='schedule'){renderSchedule();go('redesign-schedule')}syncNav();if(changed)sectionTop()}
openProjectFromSidebar=async function(id){if(window.JJTestWorkPay?.flushEdits&&!await JJTestWorkPay.flushEdits())return;const p=state.projects.find(p=>String(p.id)===String(id));if(!p)return;const route=active;state.selectedProjectId=p.id;saveState(false);renderAll();navigate(route);document.body.classList.remove('redesign-sidebar-open')};
function moneyCents(n){return money(n/100)}
async function costs(filter=team){if(!window.JJTestWorkPay)throw Error('Job costs are still loading. Please retry.');await JJTestWorkPay.refresh();const list=JJTestWorkPay.costEntries();return state.projects.map(p=>{const totals={builder:0,baseline:0,committed:0,touchup:0,pending:0};for(const r of list.filter(r=>r.projectId===String(p.id)&&(filter==='all'||r.kind===filter))){totals.estimatedBaseline||=r.estimatedBaseline;totals.builder+=r.builder;totals.baseline+=r.baseline;totals.committed+=r.committed;totals.touchup+=r.touchup;totals.pending+=r.pending}return {p,...totals}})}
function sumRows(list){return list.reduce((a,r)=>{for(const k of ['builder','baseline','committed','touchup','pending'])a[k]+=r[k];a.estimatedBaseline||=r.estimatedBaseline;return a},{builder:0,baseline:0,committed:0,touchup:0,pending:0})}
function costScale(values){const max=Math.max(0,...values);if(!max)return 100;const raw=max/4,power=10**Math.floor(Math.log10(raw)),step=[1,2,2.5,5,10].find(n=>n*power>=raw)*power;return step*4}
function graph(c,label,scale,horizontal=false,filter=team){
 const retained=c.builder-c.committed-c.pending-c.touchup,planned=c.builder-c.baseline-c.touchup,gain=retained-planned;
 const stateLabel=gain>0?'Above Plan':gain<0?'Below Plan':'On Plan',kind=filter==='subs'?'Subs':filter==='house'?'In-house':'All payouts';
 const bars=[['Baseline',c.baseline,'Original payout budget'],['Committed',c.committed,'Approved P.O.s'],['Builder cost',c.builder,'Estimated scope cost']];
 const ticks=[4,3,2,1,0].map(i=>moneyCents(scale*i/4));
 return `<article class="card rd-cost-card rd-reference-cost"><div class="rd-cost-head"><div><div class="eyebrow">${E(label)}</div><h3>${filter==='subs'?'Projected amount retained':'Projected reserve'}</h3><div class="rd-reserve-line"><strong>${moneyCents(retained)}</strong><span class="rd-cost-status ${gain>0?'positive':gain<0?'negative':'neutral'}">${stateLabel} · ${gain>0?'+':''}${moneyCents(gain)}${planned>0?' · '+(gain/planned*100).toFixed(1)+'%':''}</span></div></div><span class="rd-cost-team">${kind}</span></div>
 ${horizontal?`<div class="rd-cost-horizontal">${bars.map(([name,n,desc])=>`<div class="rd-cost-hrow"><div><span>${name} <small>· ${desc}</small></span><b>${moneyCents(n)}</b></div><div class="rd-cost-htrack"><i data-cost-bar="${name}" style="width:${Math.max(0,n/scale*100)}%" role="img" aria-label="${name}: ${moneyCents(n)}"></i></div></div>`).join('')}<div class="rd-cost-xticks">${[...ticks].reverse().map(t=>`<span>${t}</span>`).join('')}</div></div>`:
 `<div class="rd-cost-plot"><div class="rd-cost-axis">${ticks.map(t=>`<span>${t}</span>`).join('')}</div><div><div class="rd-cost-columns">${bars.map(([name,n])=>`<div class="rd-cost-column" data-cost-bar="${name}" style="height:${Math.max(0,n/scale*100)}%" role="img" aria-label="${name}: ${moneyCents(n)}"><b>${moneyCents(n)}</b></div>`).join('')}</div><div class="rd-cost-captions">${bars.map(([name,,desc])=>`<div><b>${name}</b><small>${desc}</small></div>`).join('')}</div></div></div>`}
 <div class="rd-cost-metrics"><div><span>${filter==='subs'?'Planned amount retained':'Planned reserve'}</span><b>${moneyCents(planned)}</b></div><div><span>Reserve variance</span><b>${gain>0?'+':''}${moneyCents(gain)}</b></div><div><span>Touch-up allocation</span><b>${moneyCents(c.touchup)}</b></div></div>
 <p class="rd-cost-explanation">${gain>0?moneyCents(gain)+' more retained than planned.':gain<0?moneyCents(-gain)+' less retained than planned.':'Projected retention matches the baseline.'} ${c.pending>0?moneyCents(c.pending)+' is still reserved for unapproved work.':''}</p>
 ${c.estimatedBaseline?'<p class="help-text">Legacy split: original scope allocation was not recorded; its baseline allocation is estimated.</p>':''}<p class="help-text">Projected reserve = builder cost − committed − pending allowance − touch-up. Committed means approved, not paid.</p></article>`;
}
let costRequest=0;
async function renderCosts(){const request=++costRequest,filter=team;const root=document.getElementById('redesign-costing');root.innerHTML='<p>Loading saved job costs…</p>';try{const all=await costs(filter);if(request!==costRequest)return;if(!compareInitialized){all.forEach(r=>chosen.add(String(r.p.id)));compareInitialized=true;}const filtered=costMode==='job'?all.filter(r=>r.p.id===selectedProject().id):costMode==='compare'?all.filter(r=>chosen.has(String(r.p.id))):all;const sum=sumRows(filtered),scale=costScale((costMode==='summary'?[sum]:filtered).flatMap(r=>[r.builder,r.baseline,r.committed]));root.innerHTML=`<div class="page-title"><h2>Job Costing</h2></div><div class="toolbar">${[['job','This Job'],['summary','All Jobs Summary'],['compare','Compare Jobs']].map(([v,label])=>`<button aria-pressed="${costMode===v}" onclick="JJRedesign.costView('${v}')">${label}</button>`).join('')}</div><div class="toolbar">${[['all','All'],['house','In-house'],['subs','Subs']].map(([v,label])=>`<button aria-pressed="${team===v}" onclick="JJRedesign.costTeam('${v}')">${label}</button>`).join('')}</div>${costMode==='compare'?`<div class="toolbar">${all.map(r=>`<label><input type="checkbox" ${chosen.has(String(r.p.id))?'checked':''} data-job-id="${E(r.p.id)}" onchange="JJRedesign.compareJob(this.dataset.jobId,this.checked)"> ${E(r.p.name)}</label>`).join('')}</div>`:''}<div class="rd-cost-grid">${costMode==='summary'?graph(sum,'All jobs',scale,true,filter):filtered.map(r=>graph(r,r.p.name,scale,false,filter)).join('')||'<p>No jobs selected.</p>'}</div>`}catch(e){if(request!==costRequest)return;root.innerHTML=`<h2>Job Costing</h2><p>${E(e.message)}</p><button onclick="JJRedesign.costView('job')">Retry</button>`}}
function calendarDate(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function calendarRuns(events){
 const groups=new Map(),norm=v=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');
 for(const e of events){const job=e.projectId||norm(e.location)||String(e.id).split('|')[0];const key=JSON.stringify([job,norm(e.title)]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(e)}
 const runs=[];for(const rows of groups.values()){rows.sort((a,b)=>a.date.localeCompare(b.date));let run;
 for(const e of rows){if(run&&e.date===run.end)continue;const next=run?new Date(run.end+'T12:00:00'):null;if(next)next.setDate(next.getDate()+1);
 if(run&&calendarDate(next)===e.date){run.end=e.date;run.events.push(e)}else{run={start:e.date,end:e.date,event:e,events:[e]};runs.push(run)}}}
 return runs.sort((a,b)=>a.start.localeCompare(b.start)||a.event.title.localeCompare(b.event.title));
}
function calendarGrid(cells,events,m){
 const runs=calendarRuns(events);
 return `<div class="rd-calendar-grid rd-span-calendar">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<b>${d}</b>`).join('')}${Array.from({length:cells.length/7},(_,w)=>{
 const days=cells.slice(w*7,w*7+7),first=calendarDate(days[0]),last=calendarDate(days[6]),lanes=[];
 const bars=runs.filter(r=>r.end>=first&&r.start<=last).map(r=>{const start=Math.max(0,days.findIndex(d=>calendarDate(d)>=r.start)),end=r.end>=last?6:days.findIndex(d=>calendarDate(d)===r.end);let lane=0;while(lanes[lane]!=null&&lanes[lane]>=start)lane++;lanes[lane]=end;return {r,start,end,lane}});
 return `<div class="rd-calendar-week" style="grid-template-rows:32px repeat(${Math.max(1,lanes.length)},minmax(32px,auto)) 12px">${days.map((d,i)=>`<div class="rd-calendar-day ${d.getMonth()!==m?'rd-outside':''} ${calendarDate(d)===calendarDate(new Date())?'rd-today':''}" style="grid-column:${i+1};grid-row:1 / ${Math.max(1,lanes.length)+3}"><strong>${d.getDate()}</strong></div>`).join('')}${bars.map(({r,start,end,lane})=>{const e=r.event,job=state.projects.find(p=>String(p.id)===String(e.projectId));return `<button class="rd-calendar-event rd-calendar-span" style="grid-column:${start+1} / ${end+2};grid-row:${lane+2};--event-color:${E(projectColorHex(job?.color))}" data-calendar-event="${E(e.id)}" data-calendar-start="${E(r.start)}" data-calendar-end="${E(r.end)}" onclick="JJRedesign.event(this.dataset.calendarEvent,this.dataset.calendarStart,this.dataset.calendarEnd)" title="${E([job?.name||e.location,e.title,JJDisplayDate(r.start)+' – '+JJDisplayDate(r.end)].filter(Boolean).join(' · '))}"><span class="rd-calendar-job-name">${E(job?.name||e.location||'Job name not provided')}</span><span class="rd-calendar-task-name">${r.start<first?'← ':''}${E(e.title)}${r.end>last?' →':''}</span></button>`}).join('')}</div>`}).join('')}</div>`;
}

function scheduleHTML(all=false){
 const p=selectedProject(),events=JJCalendar.reconcile(state.redesignSchedule||[],state.projects).filter(e=>all||String(e.projectId)===String(p?.id));
 const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();
 const weekStart=new Date(month);weekStart.setDate(weekStart.getDate()-weekStart.getDay());
 const cells=scheduleView==='week'?Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);return d}):Array.from({length:Math.ceil((first+days)/7)*7},(_,i)=>new Date(y,m,i-first+1));
 const title=scheduleView==='week'?JJDisplayDate(calendarDate(weekStart))+' – '+JJDisplayDate(calendarDate(cells[6])):month.toLocaleDateString('en-US',{month:'long',year:'numeric'});
 const jobs=all?state.projects:[p].filter(Boolean),legend=jobs.map(job=>`<span><i style="background:${E(projectColorHex(job.color))}"></i>${E(job.name)}</span>`).join('');
 const rows=events.filter(e=>e.date.slice(0,7)===calendarDate(month).slice(0,7));
 return `<section class="card rd-calendar rd-reference-calendar ${calendarExpanded?'rd-items-expanded':'rd-items-collapsed'}"><div class="rd-calendar-heading"><div><div class="eyebrow">${all?'Team schedule':'Job schedule'}</div><h3>${E(title)}</h3></div><div class="rd-calendar-paging"><button aria-label="Previous ${scheduleView==='week'?'week':'month'}" onclick="JJRedesign.month(-1)">←</button><button onclick="JJRedesign.today()">Today</button><button aria-label="Next ${scheduleView==='week'?'week':'month'}" onclick="JJRedesign.month(1)">→</button></div></div>${calendarTools()}<div class="rd-calendar-legend">${legend}${all&&events.some(e=>!e.projectId)?'<span><i style="background:#8193a4"></i>Unassigned job</span>':''}</div>
 ${scheduleView==='list'?`<div>${rows.map(e=>`<div class="rd-task rd-calendar-list-item" style="border-left:8px solid ${E(projectColorHex(state.projects.find(p=>String(p.id)===String(e.projectId))?.color))}"><div><button class="rd-calendar-list-title" data-calendar-event="${E(e.id)}" onclick="JJRedesign.event(this.dataset.calendarEvent)">${E(e.title)}</button><p>${E(JJDisplayDate(e.date))} · ${E(e.time||'')} · ${E(state.projects.find(p=>String(p.id)===String(e.projectId))?.name||e.location||'Job name not provided')}</p></div></div>`).join('')||'<p>No events this month.</p>'}</div>`:
 calendarGrid(cells,events,m)}</section>`;
}
function renderSchedule(){document.getElementById('redesign-schedule').innerHTML=`<div class="page-title rd-schedule-title"><div><div class="eyebrow">Job schedule</div><h2>${E(selectedProject().name)}</h2><p>Scheduled work for this job.</p></div><button class="btn" onclick="JJRedesign.navigate('dashboard')">← All jobs</button></div>`+scheduleHTML()}
function calendarTools(){return `<div class="rd-calendar-controls"><div class="rd-calendar-views">${['month','week','list'].map(v=>`<button onclick="JJRedesign.scheduleView('${v}')" aria-pressed="${scheduleView===v}">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div><div class="rd-calendar-expansion" role="group" aria-label="Calendar item detail"><button data-calendar-expand="true" aria-pressed="${calendarExpanded}" onclick="JJRedesign.expandCalendar(true)">Expand all</button><button data-calendar-expand="false" aria-pressed="${!calendarExpanded}" onclick="JJRedesign.expandCalendar(false)">Collapse all</button></div><div class="rd-calendar-feed"><button onclick="JJRedesign.refreshCalendar()">Refresh calendar</button><details class="rd-calendar-settings"><summary>Calendar options</summary><div><label class="btn">Import calendar (.ics)<input type="file" accept=".ics,text/calendar" onchange="JJRedesign.importCalendar(this)" hidden></label><button onclick="JJRedesign.subscription()">${state.calendarSubscription?'Edit subscription':'Connect subscription'}</button></div></details></div></div><p class="rd-calendar-status" role="status">${E(calendarConnectionText())} · ${E(calendarMessage||state.calendarUpdatedAt&&'Last updated '+new Date(state.calendarUpdatedAt).toLocaleString('en-US',{month:'2-digit',day:'2-digit',year:'numeric',hour:'numeric',minute:'2-digit'})||'Read-only calendar · Import or connect a calendar to show events')}</p>`}

function showCalendar(){active==='dashboard'?renderDashboard():renderSchedule()}
function applyCalendar(text){const parsed=JJCalendar.parse(text,state.projects);state.redesignSchedule=JJCalendar.reconcile(parsed.events,state.projects,state.redesignSchedule||[]);state.calendarThrough=parsed.through;state.calendarUpdatedAt=new Date().toISOString();saveState(false);calendarMessage='';showCalendar()}
async function importCalendar(input){const file=input.files[0];if(!file)return;try{const text=await file.text(),parsed=JJCalendar.parse(text,state.projects);if(!confirm(`Replace the test calendar with ${parsed.events.length} dated occurrences?`))return;applyCalendar(text);toast('Calendar imported')}catch(e){alert(e.message)}finally{input.value=''}}
let calendarBusy=false,lastCalendarAttempt=0;
function calendarConnectionText(){return state.calendarSubscription?'Subscription saved · Auto-refresh every 5 minutes while open':'No subscription connected'}
function calendarStatus(){document.querySelectorAll('.rd-calendar-status').forEach(el=>el.textContent=[calendarConnectionText(),calendarMessage|| (state.calendarUpdatedAt?'Last updated '+new Date(state.calendarUpdatedAt).toLocaleString('en-US',{month:'2-digit',day:'2-digit',year:'numeric',hour:'numeric',minute:'2-digit'}):'')].filter(Boolean).join(' · '))}
async function refreshCalendar(){
 const url=state.calendarSubscription;if(!url){calendarMessage='Connect a subscription first, or import an .ics file.';calendarStatus();return}if(calendarBusy)return;
 calendarBusy=true;lastCalendarAttempt=Date.now();const owner=cloudClient;let account=null;calendarMessage='Refreshing…';calendarStatus();
 try{
  if(!cloudClient)throw Error('Sign in to refresh the calendar.');
  account=(await cloudClient.auth.getSession()).data?.session?.user?.id;if(!account)throw Error('Sign in to refresh the calendar.');
  const {data,error}=await cloudClient.functions.invoke('jj-calendar',{body:{url}});
  if(error)throw Error('Calendar server could not refresh. Your saved schedule is unchanged.');
  if(!data?.ics)throw Error(data?.error||'The server did not return a calendar.');
  if(cloudClient!==owner||state.calendarSubscription!==url||(await cloudClient.auth.getSession()).data?.session?.user?.id!==account)return;
  const parsed=JJCalendar.parse(data.ics,state.projects);
  state.redesignSchedule=JJCalendar.reconcile(parsed.events,state.projects,state.redesignSchedule||[]);state.calendarThrough=parsed.through;state.calendarUpdatedAt=data.fetchedAt||new Date().toISOString();saveState(false);calendarMessage='';
  if(['dashboard','schedule'].includes(active))showCalendar();else calendarStatus();
 }catch(e){if(cloudClient===owner&&state.calendarSubscription===url){calendarMessage=e.message||'Refresh failed. Your saved schedule is unchanged.';calendarStatus()}}finally{calendarBusy=false;}
}
function calendarEvent(id,startDate,endDate){
 const event=(state.redesignSchedule||[]).find(e=>e.id===id);if(!event)return;
 document.getElementById('jjCalendarEvent')?.close();
 const job=state.projects.find(p=>String(p.id)===String(event.projectId));
 const clean=value=>String(value||'').replace(/https?:\/\/[^\s<>]+/gi,'').trim();
 const dialog=document.createElement('dialog');dialog.id='jjCalendarEvent';dialog.setAttribute('aria-labelledby','jjCalendarEventTitle');
 dialog.style.cssText='width:min(600px,calc(100vw - 32px));max-height:85vh;overflow:auto;box-sizing:border-box;padding:24px;border:1px solid #b49a60;border-radius:16px;background:var(--surface,#193247);color:var(--text,#e5edf5)';
 const field=(label,value)=>value?`<div style="margin:16px 0"><strong>${E(label)}</strong><div style="white-space:pre-wrap;overflow-wrap:anywhere;margin-top:5px">${E(value)}</div></div>`:'';
 dialog.innerHTML=`<div style="border-left:4px solid #b49a60;padding:12px 16px;margin-bottom:20px;background:var(--surface-raised,rgba(93,145,187,.15));border-radius:8px"><div style="font-size:12px;font-weight:700;letter-spacing:.08em;margin-bottom:6px">JOB / CUSTOMER</div><div style="font-size:24px;font-weight:750;overflow-wrap:anywhere">${E(job?.name||clean(event.location)||'Job name not provided')}</div></div><h2 id="jjCalendarEventTitle">${E(clean(event.title)||'Calendar event')}</h2>${field('Project',job?.type||job?.projectType)}${field('Job number',job?.jobNo)}${field('Date',startDate&&endDate&&startDate!==endDate?JJDisplayDate(startDate)+' – '+JJDisplayDate(endDate):JJDisplayDate(event.date))}${field('Time',event.time||'All day')}${job&&clean(event.location)!==job.name?field('Job location / details',clean(event.location)):''}${field('Assigned to',clean(event.attendees))}${field('Details',clean(event.description)||'No additional details supplied by Buildertrend.')}<div style="display:flex;justify-content:flex-end;margin-top:20px"><button class="btn btn-gold" type="button">Close</button></div>`;
 document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.showModal();
}

function subscription(){
 if(document.getElementById('jjCalendarConnection'))return;
 const dialog=document.createElement('dialog');dialog.id='jjCalendarConnection';dialog.style.cssText='width:min(560px,calc(100vw - 32px));box-sizing:border-box;padding:24px;border:1px solid #b49a60;border-radius:16px;background:var(--surface,#193247);color:var(--text,#e5edf5)';
 dialog.innerHTML='<form><h2>Calendar subscription</h2><p>Your link stays saved. Refresh checks for changes every five minutes while the app is open.</p><label for="jjCalendarURL">Buildertrend subscription link</label><input id="jjCalendarURL" type="url" required autocomplete="off" style="display:block;width:100%;box-sizing:border-box;margin:12px 0" placeholder="https://api.buildertrend.net/…"><p role="status"></p><div style="display:flex;gap:12px;justify-content:flex-end"><button type="button" class="btn">Cancel</button><button type="submit" class="btn btn-gold">Save subscription</button></div></form>';
 document.body.append(dialog);const input=dialog.querySelector('input');input.value=state.calendarSubscription||'';
 dialog.querySelector('[type=button]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
 dialog.querySelector('form').onsubmit=event=>{event.preventDefault();try{const u=new URL(input.value.trim());if(u.protocol!=='https:'||u.hostname!=='api.buildertrend.net'||(u.port&&u.port!=='443')||u.pathname!=='/v2/Schedules/external-calendar'||u.username||u.password||u.hash||!u.searchParams.get('token')||[...u.searchParams.keys()].some(k=>k!=='token'))throw Error('Enter your Buildertrend HTTPS calendar subscription link.');state.calendarSubscription=u.href;saveState(false);dialog.close();refreshCalendar();}catch(e){dialog.querySelector('[role=status]').textContent=e.message}};
 dialog.showModal();input.focus();
}

let dashboardTeam='all',dashboardRequest=0;
function nextSection(p){return (p.preconData||[]).findIndex((s,i)=>s.status!=='Complete'&&!(typeof sectionPct==='function'&&sectionPct(p,i)===100))}
function nextTask(p){const i=nextSection(p);return `<div class="rd-task"><div><h4>${E(p.name)}</h4><p>${i<0?'Checklist complete':`${i+1}. ${E(PRECON_SECTIONS[i]?.title||'Next step')}`}</p><p>${i<0?'All sections completed':`Responsible: ${['Gio','Jony','Jony','Adair','Adair','Adair','Everyone'][i]||'Everyone'}`}</p></div><button class="btn btn-light" data-job-id="${E(p.id)}" onclick="JJRedesign.openJob(this.dataset.jobId,'preconstruction')">${i<0?'Review checklist':'View current step'}</button></div>`}
async function dashboardCosts(){const target=document.getElementById('rdDashboardGraph');if(!target)return;const request=++dashboardRequest,filter=dashboardTeam;try{if(!window.JJTestWorkPay){target.innerHTML='<p class="rd-empty">Sign in to load saved job costs.</p>';return}const rows=await costs(filter);if(request!==dashboardRequest||!target.isConnected)return;const total=sumRows(rows),scale=costScale([total.builder,total.baseline,total.committed]);target.innerHTML=graph(total,'All jobs',scale,true,filter)}catch(e){if(request===dashboardRequest&&target.isConnected)target.innerHTML=`<p class="rd-empty">${E(e.message)}</p><button class="btn" onclick="JJRedesign.dashboardTeam('${filter}')">Retry</button>`}}
const oldDashboard=renderDashboard;renderDashboard=function(){oldDashboard();ensurePreconData();const root=document.getElementById('dashboard');const legacy=document.createElement('div');while(root.firstChild)legacy.append(root.firstChild);const now=new Date();now.setHours(0,0,0,0);const end=new Date(now);end.setDate(end.getDate()+30);const soon=state.projects.map(p=>({p,date:new Date(p.start)})).filter(x=>Number.isFinite(+x.date)&&x.date>=now&&x.date<=end).sort((a,b)=>a.date-b.date).slice(0,3);
root.innerHTML=scheduleHTML(true)+`<section class="card rd-panel rd-dashboard-costs"><div class="rd-section-head"><div><h3>Job costing · All jobs</h3><p>Baseline, committed payout, and builder cost</p></div><div class="rd-filters">${[['all','All'],['house','In-house'],['subs','Subs']].map(([v,label])=>`<button aria-pressed="${dashboardTeam===v}" onclick="JJRedesign.dashboardTeam('${v}')">${label}</button>`).join('')}<button onclick="JJRedesign.costView('compare');JJRedesign.navigate('costing')">Compare jobs →</button></div></div><div id="rdDashboardGraph">Loading saved job costs…</div></section><section class="card rd-panel"><div class="rd-section-head"><div><h3>Soon to start</h3><p>Next 30 days · Up to 3 jobs</p></div><button class="btn btn-gold" onclick="openNewProject()">+ New job</button></div>${soon.map(({p})=>`<div class="rd-task"><div><h4>${E(p.name)}</h4><p>Planned start: ${E(JJDisplayDate(p.start))}</p></div><button class="btn btn-gold" data-job-id="${E(p.id)}" onclick="JJRedesign.openJob(this.dataset.jobId,'preconstruction')">Open job →</button></div>`).join('')||'<p class="rd-empty">No jobs scheduled to start in the next 30 days.</p>'}</section><section class="card rd-panel"><div class="rd-section-head"><div><h3>Preconstruction · Next step</h3><p>One next step per job. Later steps appear after earlier ones are complete.</p></div></div>${state.projects.map(nextTask).join('')}</section><section class="card rd-panel"><h3>Inspections</h3><p>Review inspection requirements and scheduling in each job’s checklist.</p>${state.projects.map(p=>{const items=(p.preconData||[]).flatMap(s=>s.items||[]).filter(i=>/inspection/i.test(i.text||i.label||''));return `<div class="rd-task"><div><h4>${E(p.name)}</h4><p>${items.length?items.map(i=>`${i.done?'✓':'○'} ${E(i.text||i.label)}`).join(' · '):'Inspection requirements need review'}</p></div><button class="btn" data-job-id="${E(p.id)}" onclick="JJRedesign.openJob(this.dataset.jobId,'preconstruction')">Review inspections</button></div>`}).join('')}</section>`;
if(window.JJUpgrade?.dashboardInspections){const sections=root.querySelectorAll(':scope > section');sections[sections.length-1]?.remove();root.insertAdjacentHTML('beforeend',JJUpgrade.dashboardInspections());}
const extra=document.createElement('details');extra.className='rd-extra-reports';extra.innerHTML='<summary>More job reports and existing dashboard tools</summary>';extra.append(legacy);root.append(extra);dashboardCosts();};
// Preserve existing project panels, admin tools, backup controls, imports and print paths.
function expandCalendar(expanded){
 calendarExpanded=!!expanded;
 document.querySelectorAll('.rd-reference-calendar').forEach(el=>{el.classList.toggle('rd-items-expanded',calendarExpanded);el.classList.toggle('rd-items-collapsed',!calendarExpanded)});
 document.querySelectorAll('[data-calendar-expand]').forEach(el=>el.setAttribute('aria-pressed',String((el.dataset.calendarExpand==='true')===calendarExpanded)));
}
window.JJRedesign={expandCalendar,navigate,theme,scheduleView:v=>{if(!['month','week','list'].includes(v))return;scheduleView=v;showCalendar()},today:()=>{month=new Date();showCalendar()},refreshCalendar,subscription,openJob:(id,section)=>{const p=state.projects.find(p=>String(p.id)===id);if(!p)return;state.selectedProjectId=p.id;saveState(false);renderAll();navigate(section)},dashboardTeam:v=>{dashboardTeam=v;renderDashboard()},costView:v=>{costMode=v;renderCosts()},costTeam:v=>{team=v;renderCosts()},compareJob:(id,on)=>{on?chosen.add(id):chosen.delete(id);renderCosts()},month:n=>{month=scheduleView==='week'?new Date(month.getFullYear(),month.getMonth(),month.getDate()+n*7):new Date(month.getFullYear(),month.getMonth()+n,1);active==='dashboard'?renderDashboard():renderSchedule()},importCalendar,event:calendarEvent};
window.addEventListener('jj-workpay-ready',()=>{if(active==='dashboard')dashboardCosts()});
function autoCalendar(){if(!document.hidden&&state.calendarSubscription&&Date.now()-lastCalendarAttempt>=300000)refreshCalendar()}
setInterval(autoCalendar,30000);document.addEventListener('visibilitychange',autoCalendar);window.addEventListener('jj-workpay-ready',autoCalendar);
let initial='night';try{initial=localStorage.getItem('jj_test_design_theme')||'night'}catch{}theme(initial);syncNav();renderDashboard();
})();
