/* R.W. is isolated from Operations app_state and the Work & Pay ledger. */
(()=>{'use strict';

const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null,people=[],requests=[],notices=[],view='mine',unread=false,busy=false,loading=false,error='',focused='',hooked=null,epoch=0,lastLoad=0;
const client=()=>typeof cloudClient!=='undefined'?cloudClient:null;
const name=id=>people.find(p=>p.id===id)?.display_name||'Internal user';
const date=v=>v?new Date(v+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'';
const host=document.createElement('section');host.id='jj-rw';host.className='jj-rw';
const bellWrap=document.createElement('div');bellWrap.className='jj-rw rw-bell-wrap';bellWrap.innerHTML='<button type="button" id="rw-bell" aria-label="R.W. notifications" aria-expanded="false" aria-controls="rw-inbox">🔔 <span>R.W.</span> <b id="rw-badge" hidden></b></button><section id="rw-inbox" hidden aria-label="R.W. notifications"><div class="rw-head"><h3>R.W. Notifications</h3><button data-rw="close-inbox" aria-label="Close notifications">Close</button></div><div class="rw-tools"><div><button data-rw="all-notices">All</button> <button data-rw="unread">Unread</button></div><button data-rw="read-all">Mark all as read</button></div><div id="rw-notices"></div><div id="rw-inbox-error" role="status"></div></section>';
const dialog=document.createElement('dialog');dialog.id='rw-dialog';dialog.className='jj-rw';document.body.append(dialog);
function mount(){const dash=document.getElementById('dashboard');if(dash&&!host.isConnected)dash.prepend(host);const h=document.querySelector('.operations-header .header-actions');if(h&&!bellWrap.isConnected)h.prepend(bellWrap);render();}
function noticeText(n){return `${name(n.actor)} ${n.event==='assigned'?'assigned you a request':n.event==='completed'?'completed a request':'reopened a request'}`}
function inbox(){const count=notices.filter(n=>!n.read_at).length;const badge=bellWrap.querySelector('#rw-badge');badge.textContent=count;badge.hidden=!count;bellWrap.querySelector('#rw-bell').setAttribute('aria-label',`R.W. notifications, ${count} unread`);bellWrap.querySelector('[data-rw="read-all"]').disabled=!count||busy;bellWrap.querySelector('[data-rw="all-notices"]').setAttribute('aria-pressed',!unread);bellWrap.querySelector('[data-rw="unread"]').setAttribute('aria-pressed',unread);bellWrap.querySelector('#rw-notices').innerHTML=notices.filter(n=>!unread||!n.read_at).map(n=>{const r=requests.find(r=>r.id===n.request_id);return `<button class="rw-notice" data-rw="notice" data-id="${E(n.id)}" data-unread="${!n.read_at}"><span class="rw-dot"></span><span>${E(noticeText(n))}<small>${E(r?.title||'Work request')} · ${E(r?.job_name||'')}</small><small>${E(new Date(n.created_at).toLocaleString())} · ${n.read_at?'Read':'Unread'}</small></span></button>`}).join('')||`<p class="rw-muted">${!me?'Sign in to see your notifications.':loading?'Loading…':error?'Notifications unavailable. Use Refresh in Request Work.':unread?'You’re all caught up.':'No notifications yet.'}</p>`;}
function render(){if(!host.isConnected)return;const shown=requests.filter(r=>view==='all'||(view==='mine'?r.assigned_to===me?.id:r.created_by===me?.id));host.innerHTML=`<div class="rw-head"><div class="rw-identity"><span class="rw-logo">R.W.</span><div><h2>Request Work</h2><p class="rw-muted">Jony, Adair & Gio</p></div></div><button class="rw-gold" data-rw="new" ${!me||!people.length?'disabled':''}>+ Request work</button></div><div class="rw-tools"><div class="rw-tabs">${[['mine','My Requests'],['sent','Sent by Me'],['all','All Requests']].map(([v,l])=>`<button data-rw="view" data-view="${v}" aria-pressed="${view===v}">${l}</button>`).join('')}</div><button data-rw="refresh">Refresh</button></div>${error?`<p class="rw-error" role="status">${E(error)}</p>`:''}<div class="rw-cards">${shown.map(r=>`<article class="rw-item" data-request="${r.id}" data-focused="${focused===r.id}"><div class="rw-muted">${E(r.job_name)}</div><div class="rw-head"><h3>${E(r.title)}</h3><span class="rw-status">${E(r.status)}</span></div><p class="rw-description">${E(r.description)}</p><div class="rw-foot"><div class="rw-person"><span class="rw-avatar">${E(name(r.assigned_to)[0])}</span><div>${E(name(r.assigned_to))}<small>Requested by ${E(name(r.created_by))}</small></div></div><div class="rw-actions">${r.due_date?`<span class="rw-muted">Due ${date(r.due_date)}</span>`:''}<button data-rw="details" data-id="${r.id}">Details</button>${[r.created_by,r.assigned_to].includes(me?.id)?`<button class="${r.status==='Completed'?'rw-red':'rw-gold'}" data-rw="status" data-id="${r.id}" ${busy?'disabled':''}>${r.status==='Completed'?'Reopen request':'Mark completed'}</button>`:''}</div></div></article>`).join('')||`<p class="rw-muted">${!me?'Sign in to load requests.':loading?'Loading requests…':'No requests in this view.'}</p>`}</div><p class="rw-muted rw-sync">${me?'Saved · R.W. only':''}</p>`;inbox();}
async function refresh(force=false){if(loading||(!force&&Date.now()-lastLoad<15000))return;const c=client();if(!c)return;loading=true;const current=epoch;try{const {data,error:e}=await c.auth.getUser();if(e)throw e;if(current!==epoch)return;const user=data.user;if(!user){clear();return}if(me&&me.id!==user.id){clear();return refresh(true)}me=user;
const results=await Promise.all([c.from('profiles').select('id,display_name').in('display_name',['Jony','Adair','Gio']),c.from('jj_rw_requests').select('id,title,description,job_id,job_name,created_by,assigned_to,due_date,status,revision,created_at,updated_at').order('created_at',{ascending:false}),c.from('jj_rw_notifications').select('*').order('created_at',{ascending:false})]);if(current!==epoch)return;for(const r of results)if(r.error)throw r.error;people=results[0].data||[];if(!people.some(p=>p.id===me.id))throw Error('R.W. is available to Jony, Adair and Gio only.');requests=results[1].data||[];notices=results[2].data||[];error='';lastLoad=Date.now();}catch(e){if(current===epoch)error='R.W. could not refresh. '+(e.message||'Check your connection.');}finally{if(current===epoch){loading=false;render()}}}
function clear(){epoch++;me=null;people=[];requests=[];notices=[];loading=false;busy=false;error='';lastLoad=0;if(dialog.open)dialog.close();setInbox(false);render()}
async function rpc(n,args){const c=client();if(!c||!me)throw Error('Sign in first.');const result=await c.rpc(n,args);if(result.error)throw result.error;return result.data;}
function setInbox(open){bellWrap.querySelector('#rw-inbox').hidden=!open;bellWrap.querySelector('#rw-bell').setAttribute('aria-expanded',String(open))}
async function mark(ids){if(!ids.length)return;await rpc('jj_rw_read',{p_ids:ids});notices.forEach(n=>{if(ids.includes(n.id))n.read_at=n.read_at||new Date().toISOString()});inbox();}
function modal(html){dialog.innerHTML=html;if(!dialog.open)dialog.showModal()}
function newRequest(){const jobs=typeof state!=='undefined'?state.projects||[]:[];modal(`<form id="rw-create"><div class="rw-head"><h2>New request</h2><button type="button" data-rw="close-dialog">Cancel</button></div><p class="rw-muted">Requested by ${E(name(me.id))}</p><div class="rw-fields"><label>Assigned to<select name="person" required><option value="">Choose a person</option>${people.map(p=>`<option value="${p.id}">${E(p.display_name)}</option>`).join('')}</select></label><label>Job<select name="job"><option value="">General J&J Work</option>${jobs.map(p=>`<option value="${E(p.id)}">${E(p.name)}</option>`).join('')}</select></label><label class="rw-full">Request title<input name="title" required maxlength="100"></label><label class="rw-full">Description<textarea name="description" rows="3" required maxlength="5000"></textarea></label><label>Due date (optional)<input type="date" name="due"></label><label>Photos / attachments (optional)<input name="attachments" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple><small>Up to 3 JPG, PNG, WebP or PDF files · 2 MB total</small></label></div><p id="rw-form-error" class="rw-error" role="alert"></p><div class="rw-actions"><button type="submit" class="rw-gold">Create request</button></div></form>`);const form=dialog.querySelector('form');form.dataset.requestId=crypto.randomUUID();form.onsubmit=async e=>{e.preventDefault();if(busy)return;const fields=form.elements;if(!fields.title.value.trim()||!fields.description.value.trim())return;busy=true;form.querySelector('[type=submit]').disabled=true;try{const files=[...fields.attachments.files];if(files.length>3||files.reduce((n,f)=>n+f.size,0)>2*1024*1024)throw Error('Choose up to 3 files, 2 MB total.');const attachments=await Promise.all(files.map(f=>new Promise((resolve,reject)=>{if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type))return reject(Error('Use JPG, PNG, WebP or PDF.'));const rd=new FileReader();rd.onerror=()=>reject(Error('Could not read attachment'));rd.onload=()=>resolve({name:f.name.slice(0,150),type:f.type,data:rd.result});rd.readAsDataURL(f)})));await rpc('jj_rw_create',{p_id:form.dataset.requestId,p_title:fields.title.value.trim(),p_description:fields.description.value.trim(),p_job_id:fields.job.value||null,p_job_name:fields.job.selectedOptions[0].textContent,p_assigned_to:fields.person.value,p_due_date:fields.due.value||null,p_attachments:attachments});dialog.close();view='sent';await refresh(true);}catch(e){dialog.querySelector('#rw-form-error').textContent=e.message||'Could not save. Your draft is still here.';}finally{busy=false;form.querySelector('[type=submit]').disabled=false;render()}};}
async function details(id){const r=requests.find(r=>r.id===id);if(!r)return;modal(`<div class="rw-head"><h2>${E(r.title)}</h2><button data-rw="close-dialog">Close</button></div><p class="rw-muted">${E(r.job_name)} · ${E(r.status)}</p><p class="rw-description">${E(r.description)}</p><p>Assigned to ${E(name(r.assigned_to))} · Requested by ${E(name(r.created_by))}</p><div id="rw-files">Loading attachments…</div>`);const result=await client().from('jj_rw_requests').select('attachments').eq('id',id).single();const el=dialog.querySelector('#rw-files');if(!el)return;if(result.error){el.textContent='Attachments could not load.';return}el.textContent='';const files=result.data?.attachments||[];if(!files.length)el.textContent='No attachments.';files.forEach(f=>{const a=document.createElement('a');a.textContent=f.name;a.href=f.data;a.download=f.name;a.className='rw-file';el.append(a)});}
async function action(e){const b=e.target.closest('[data-rw]');if(!b)return;const a=b.dataset.rw;try{if(a==='view'){view=b.dataset.view;render()}if(a==='refresh')await refresh(true);if(a==='new')newRequest();if(a==='close-dialog'&&!busy)dialog.close();if(a==='details')await details(b.dataset.id);if(a==='close-inbox')setInbox(false);if(a==='unread'||a==='all-notices'){unread=a==='unread';inbox()}if(a==='read-all')await mark(notices.filter(n=>!n.read_at).map(n=>n.id));if(a==='notice'){
 const n=notices.find(n=>String(n.id)===b.dataset.id);if(!n)return;
 setInbox(false);focused=n.request_id;view='all';
 if(window.JJRedesign)await JJRedesign.navigate('dashboard');else go('dashboard');
 // Navigation may be cancelled by another section's unsaved-edit protection.
 if(!document.getElementById('dashboard')?.classList.contains('active'))return;
 mount();const card=host.querySelector(`[data-request="${CSS.escape(n.request_id)}"]`);
 if(!card){error='This request is no longer available. Refresh the request list.';render();return;}
 card.setAttribute('tabindex','-1');card.focus({preventScroll:true});
 card.style.scrollMarginTop=((document.getElementById('redesignChrome')?.getBoundingClientRect().height||80)+20)+'px';
 card.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 await mark([n.id]);
 }if(a==='status'&&!busy){const r=requests.find(r=>r.id===b.dataset.id);busy=true;render();try{await rpc('jj_rw_status',{p_id:r.id,p_revision:r.revision,p_status:r.status==='Completed'?'Requested':'Completed'});await refresh(true)}finally{busy=false;render()}}}catch(e){error=e.message||'Could not save. Try again.';bellWrap.querySelector('#rw-inbox-error').textContent=error;render()}}
host.addEventListener('click',action);bellWrap.addEventListener('click',action);dialog.addEventListener('click',action);dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault()});bellWrap.querySelector('#rw-bell').onclick=()=>{const open=bellWrap.querySelector('#rw-inbox').hidden;setInbox(open);if(open)refresh(true)};document.addEventListener('click',e=>{if(!bellWrap.contains(e.target))setInbox(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')setInbox(false)});
const old=window.renderDashboard;window.renderDashboard=function(){const result=old.apply(this,arguments);mount();return result};
function tick(){const c=client();if(c&&hooked!==c){hooked=c;c.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){clear();return}setTimeout(()=>refresh(true),0)})}if(!document.hidden)refresh();}
mount();tick();setInterval(tick,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true)});
})();
