/* Read-only selection printing. No project or payment records are modified. */
(()=>{
'use strict';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const chosen=i=>['Selected','Ordered','Received'].includes(i.status);
const price=i=>i.unitPrice!==null&&i.unitPrice!==undefined&&i.unitPrice!==''&&Number.isFinite(Number(i.unitPrice));
const qty=i=>Math.max(1,Number(i.quantity)||1);
const cents=i=>Math.round(Number(i.unitPrice)*qty(i)*(i.addTax?1.0825:1)*100);
function url(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
function photo(value){return /^data:image\/(png|jpeg|webp|gif);base64,/i.test(value||'')?value:url(value)}
function qr(link){if(!link||typeof QRCode==='undefined')return '';try{const el=document.createElement('div');new QRCode(el,{text:link,width:150,height:150,correctLevel:QRCode.CorrectLevel.M});return el.querySelector('canvas')?.toDataURL()||el.querySelector('img')?.src||''}catch{return ''}}
function build(p,mode='selected'){
 const all=p.selections||[],items=mode==='all'?all:all.filter(chosen);
 let total=0,missing=0;
 const cards=items.map(i=>{
  const group=(p.selectionGroups||[]).find(g=>String(g.id)===String(i.optionGroupId));
  const budget=group||(!i.optionGroupId?p.selectionUngroupedBudget:null);
  const members=all.filter(x=>String(x.optionGroupId||'')===String(i.optionGroupId||''));
  const summary=window.JJGroupBudgets.summary(budget,members);
  const link=url(i.url),image=photo(i.image),code=qr(link),priced=price(i);
  if(chosen(i)){if(priced)total+=cents(i);else missing++}
  const label=group?.name||i.optionGroupTitle||i.room||'Ungrouped selections';
  const lead=i.leadTimeValue?`${i.leadTimeValue} ${i.leadTimeUnit||'days'}`:'Confirm with vendor';
  return `<article><div class="band"><b>${E(label)}</b><span>${E(i.status||'Pending')}${chosen(i)?'':' · Review only'}</span></div><div class="product"><div class="photo">${image?`<img src="${E(image)}" alt="Product photo">`:'No product photo'}</div><div><h2>${link?`<a href="${E(link)}" target="_blank" rel="noopener">${E(i.title||'Untitled selection')}</a>`:E(i.title||'Untitled selection')}</h2><p>${E(i.vendor||'Vendor not entered')} · Model / SKU ${E(i.model||'not entered')}${i.upc?` · UPC ${E(i.upc)}`:''}</p>${i.category?`<p>${E(i.category)}</p>`:''}</div><div class="qr">${code?`<a href="${E(link)}"><img src="${E(code)}" alt="Scan to open product"></a><span>Find item</span>`:link?`<a href="${E(link)}">Open product</a>`:''}</div></div><div class="numbers"><div><small>Quantity</small><strong>${E(qty(i))}</strong></div><div><small>Unit price</small><strong>${priced?money(Math.round(Number(i.unitPrice)*100)):'Not priced'}</strong></div><div><small>Item total${i.addTax?' · incl. tax':''}</small><strong>${priced?money(cents(i)):'Not priced'}</strong></div><div><small>Group budget</small><strong>${summary.budget===null?'Not set':money(summary.budget)}</strong></div><div><small>${summary.over?'Group over budget':'Group remaining'}</small><strong>${summary.budget===null?'—':money(summary.over||summary.budget-summary.total)}</strong></div></div><div class="info"><p>${budget?.budgetMode==='unit'?`<b>Budget:</b> ${money(budget.budgetUnitCents)} / ${E(budget.budgetUnit)} × ${E(budget.budgetQuantity)} ${E(budget.budgetUnit)} · `:''}<b>Group selected total:</b> ${money(summary.total)}${summary.unpriced?` · ${summary.unpriced} item(s) need pricing`:''}</p><p><b>Purchaser:</b> ${E(i.purchasedBy||'Not assigned')} · <b>Lead time:</b> ${E(lead)}</p>${i.description?`<p class="description"><b>Description:</b> ${E(i.description)}</p>`:''}${i.notes?`<p class="description"><b>Notes:</b> ${E(i.notes)}</p>`:''}</div><div class="checks">□ Reviewed &nbsp;&nbsp; □ Ordered &nbsp;&nbsp; □ Received</div><div class="write"><span>Order # / date: __________________</span><span>Expected delivery: __________________</span></div></article>`;
 }).join('');
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(p.name)} — Selections</title><style>
*{box-sizing:border-box}body{font:12px/1.4 Arial,sans-serif;color:#203044;background:#fff;margin:0;padding:20px}header{display:flex;justify-content:space-between;gap:12px;margin-bottom:16px}h1{font-size:19px;margin:0 0 4px}header p{margin:0;font-size:12px}article{border:1px solid #9da9b5;border-radius:6px;overflow:hidden;margin-bottom:14px;break-inside:avoid;page-break-inside:avoid}.band{display:flex;justify-content:space-between;gap:12px;background:#f1f3f5;border-bottom:1px solid #d4dbe1;padding:7px 12px}.product{display:grid;grid-template-columns:65px minmax(0,1fr) 82px;gap:12px;padding:12px}.photo{height:75px;border:1px solid #e0e4e8;display:flex;align-items:center;justify-content:center;text-align:center;font-size:11px;color:#596674}.photo img{width:100%;height:100%;object-fit:contain}h2{font-size:14px;margin:0 0 4px;overflow-wrap:anywhere}a{color:#203044;text-decoration:underline;text-underline-offset:2px}.product p{margin:3px 0;overflow-wrap:anywhere}.qr{text-align:center;font-size:10px;padding:3px}.qr img{width:76px;height:76px;max-width:100%;image-rendering:pixelated;display:block;margin:auto}.numbers{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;border-top:1px solid #d4dbe1;border-bottom:1px solid #d4dbe1;padding:9px 12px;background:#fafbfc}.numbers small{display:block;color:#54616d;font-size:10px;margin-bottom:2px}.numbers strong{font-size:12px;overflow-wrap:anywhere}.info{padding:8px 12px}.info p{margin:0 0 5px;overflow-wrap:anywhere}.info p:last-child{margin:0}.description{white-space:pre-wrap}.checks{border-top:1px solid #d4dbe1;padding:7px 12px}.write{display:flex;flex-wrap:wrap;gap:12px;padding:0 12px 10px;font-size:11px}.total{display:flex;justify-content:space-between;border-top:2px solid #203044;padding-top:10px;font-weight:bold;font-size:14px}footer{margin-top:6px;font-size:10px;color:#54616d}.empty{padding:24px;border:1px solid #d4dbe1}@page{size:letter;margin:0.45in}@media print{body{padding:0}header{break-inside:avoid}a{text-decoration:none}}@media screen and (max-width:480px){body{padding:12px}.product{grid-template-columns:48px minmax(0,1fr)}.qr{grid-column:2;width:82px}.numbers{grid-template-columns:repeat(2,minmax(0,1fr))}header{flex-direction:column}}
</style></head><body><header><div><h1>J&J Home Renovations</h1><p>${E(p.name)}${p.jobNo?` · ${E(p.jobNo)}`:''}</p></div><div>${mode==='all'?'Selections review':'Selected items · Order sheet'}<br>${new Date().toLocaleDateString('en-US')}</div></header>${cards||'<div class="empty">No selections in this print view.</div>'}<div class="total"><span>Selected items total</span><span>${money(total)}</span></div><footer>${missing?`${missing} selected item(s) not priced. `:''}Includes applied item tax; delivery not included. Group budgets repeat for reference and are not added together. Confirm vendor pricing and availability before ordering.</footer></body></html>`;
}
function open(){
 const project=selectedProject();if(!project)return;
 document.getElementById('jj-selection-print')?.remove();
 const dialog=document.createElement('dialog');dialog.id='jj-selection-print';
 dialog.style.cssText='width:min(900px,96vw);max-height:94dvh;padding:16px;border:1px solid #aab5c0;border-radius:12px;background:#fff;color:#203044';
 dialog.innerHTML='<div class="jj-print-toolbar"><label>Print view <select aria-label="Print view"><option value="selected">Selected items only</option><option value="all">Review all options</option></select></label><button type="button" class="btn btn-gold" data-print>Print / Save PDF</button><button type="button" class="btn" data-close>Close</button><span role="status"></span></div><iframe title="Selection print preview" style="width:100%;height:65dvh;border:1px solid #d4dbe1;background:white"></iframe>';
 document.body.append(dialog);dialog.showModal();
 const frame=dialog.querySelector('iframe'),select=dialog.querySelector('select'),button=dialog.querySelector('[data-print]'),status=dialog.querySelector('[role=status]');
 let generation=0;
 frame.onload=async()=>{const token=generation,doc=frame.contentDocument;if(!doc)return;await Promise.race([Promise.all([...doc.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve}))),new Promise(resolve=>setTimeout(resolve,8000))]);if(token!==generation||!dialog.isConnected)return;[...doc.images].filter(img=>!img.naturalWidth).forEach(img=>{const text=doc.createElement('span');text.textContent=img.alt==='Product photo'?'Photo unavailable':'Use product link';img.replaceWith(text)});button.disabled=false;status.textContent='';};
 function render(){generation++;button.disabled=true;status.textContent='Preparing print preview…';frame.srcdoc=build(project,select.value)}
 select.onchange=render;button.onclick=()=>{frame.contentWindow.focus();frame.contentWindow.print()};dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();render();
}
window.JJSelectionPrint={build,open};window.exportSelectionsPdf=open;
})();
