/* J&J Work & Pay. Additive module: existing job data is not migrated on load. */
(()=>{'use strict';
const names=['Alex M','Brandon B','Jony M','Adair L','Jony L'];
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cents=v=>Math.round(Number(v||0)*100),M=c=>money(c/100),today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;},day=s=>Date.parse(s+'T00:00:00Z')/86400000,ds=n=>new Date(n*86400000).toISOString().slice(0,10),validDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(day(s))&&ds(day(s))===s;
let doc=null,revision=0,busy=false,mode='work',kind='Everyone',period='Bi-weekly',start=ds(day(today())-new Date(today()+'T00:00:00Z').getUTCDay()),person='',job='',query='',historyStatus='All',historyMethod='All',historyFrom='',historyTo='';
const key=(p,po)=>JSON.stringify([String(p.id),String(po.id)]),clone=x=>JSON.parse(JSON.stringify(x));
function entries(){return (state.projects||[]).flatMap(p=>(p.pos||[]).map(po=>({p,po,key:key(p,po)})));}
function entry(k){return entries().find(x=>x.key===k);}
function cfg(x){return doc?.configs?.[x.key]||{sub:!!x.po.subs,subPct:x.po.subPct??75,company:x.po.subId||'',splits:clone(x.po.splits||[])};}
function description(x){if(typeof x.po.description==='string')return x.po.description;const rows=(x.p.estimate||[]).filter(r=>x.po.sourceEstimateKey?estimateRowSourceKey(r)===x.po.sourceEstimateKey:(String(r.title||r.line||'')===getPOBaseTitle(x.po)&&String(r.parentGroup||'').toLowerCase()===String(x.po.parentGroup||'').toLowerCase()&&estimatePOEligible(r)));return rows.length===1?rows[0].description||'':'';}
function alloc(x){const c=cfg(x),base=Math.round(cents(x.po.builderCost)*.6);return c.sub?[{person:doc?.companies?.[c.company]?.name||'Unassigned sub',companyId:c.company,pct:Number(c.subPct),amount:Math.round(cents(x.po.builderCost)*Number(c.subPct)/100)}]:(c.splits||[]).filter(s=>s.name&&Number(s.pct)>0).map(s=>({person:s.name,pct:Number(s.pct),amount:Math.round(base*Number(s.pct)/100)}));}
function paid(workId,name){return Object.values(doc?.payments||{}).filter(p=>!p.voided).flatMap(p=>p.lines).filter(l=>l.workId===workId&&l.person===name).reduce((s,l)=>s+l.amount,0);}
const subSelected=new Set();
function incomplete(id){return !!doc?.lifecycle?.[id]?.incomplete;}
function effectiveWork(id){const w=doc?.work?.[id],x=entry(id);return w?{...w,description:x?description(x):w.description,completedDate:doc?.lifecycle?.[id]?.completedDate||w.completedDate}:null;}
function rows(){return Object.entries(doc?.work||{}).filter(([id])=>!incomplete(id)).flatMap(([workId,original])=>{const w=effectiveWork(workId);return w.allocations.map(a=>({...a,workId,w,balance:a.amount-paid(workId,a.person)}));});}
function err(e){alert(e?.message||String(e));}
async function load(){if(!cloudClient)throw Error('Sign in to cloud before using Work & Pay.');const r=await cloudClient.rpc('jj_work_pay_read');if(r.error)throw Error('Work & Pay storage is not ready. Run WORK_PAY_SETUP.sql, then refresh. '+r.error.message);doc=r.data.document;revision=r.data.revision;return doc;}
async function change(fn){if(busy)return;busy=true;try{if(!doc)await load();const next=clone(doc);fn(next);const r=await cloudClient.rpc('jj_work_pay_save',{expected_revision:revision,new_document:next});if(r.error){await load();throw r.error;}const previous=doc;doc=r.data.document;revision=r.data.revision;let changedSplits=false;for(const x of entries()){const c=doc.configs[x.key];if(c&&JSON.stringify(c)!==JSON.stringify(previous?.configs?.[x.key])){if(!c.sub)x.po.splits=clone(c.splits);x.po.subs=c.sub;x.po.subPct=c.subPct;x.po.subId=c.company;changedSplits=true;}}if(changedSplits)saveState(false);renderPayByLine();if(document.getElementById('jj-workpay').classList.contains('active'))render();return true;}catch(e){err(e);return false;}finally{busy=false;}}
const style=document.createElement('style');style.textContent=`.jj-po-owner{margin-top:6px;font-size:12px;font-weight:700;line-height:1.4;color:var(--navy,#14234a);white-space:normal;overflow-wrap:anywhere}.po.expanded .jj-po-owner{display:none}.po.jj-po-approved:not(.expanded){border-color:var(--gold,#B59A62);background:var(--gold,#B59A62)}.po.jj-po-approved:not(.expanded)>.po-head{background:var(--gold,#B59A62)}.po.jj-po-approved:not(.expanded) .po-head h4,.po.jj-po-approved:not(.expanded) .po-head small,.po.jj-po-approved:not(.expanded) .po-parent-group-label,.po.jj-po-approved:not(.expanded) .po-chevron,.po.jj-po-approved:not(.expanded) .po-quick{color:var(--navy,#14234a)}.po.jj-po-approved:not(.expanded) .po-quick .pill{background:#fff8e5;color:#594417;border:1px solid #fff5da}#jj-workpay .toolbar{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}#jj-workpay label{display:grid;gap:5px}#jj-workpay table{width:100%;border-collapse:collapse}#jj-workpay td,#jj-workpay th{padding:12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}.jj-description{white-space:pre-wrap;overflow-wrap:anywhere;margin:8px 0;line-height:1.5}.jj-wp-dialog{width:min(960px,95vw);max-height:90vh;overflow:auto;border:1px solid var(--line);border-radius:14px;padding:24px;color:var(--text)}.jj-wp-dialog::backdrop{background:#10233899}.jj-wp-dialog table{width:100%;border-collapse:collapse}.jj-wp-dialog td,.jj-wp-dialog th{padding:10px;text-align:left;border-bottom:1px solid #ddd;vertical-align:top}.jj-wp-dialog .jj-description{max-width:470px}.jj-work-controls{border-top:1px solid var(--line);padding-top:14px;margin-top:14px}.jj-calendar{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;max-width:380px;margin:10px 0}.jj-calendar button{padding:8px}.jj-calendar button:disabled{opacity:.35}@media print{body.jj-print>*{display:none!important}body.jj-print>#jj-wp-dialog{display:block!important;position:static!important;width:100%!important;max-height:none!important;overflow:visible!important;border:0!important}body.jj-print #jj-wp-dialog button{display:none!important}body.jj-print #jj-wp-dialog .table-wrap{overflow:visible!important}}`;
style.textContent+='.po.jj-po-approved:not(.expanded){background:#EAF2FC;border-color:#BDD2EC}.po.jj-po-approved:not(.expanded)>.po-head{background:#EAF2FC}.po.jj-po-approved.jj-po-sub:not(.expanded){background:#F7F0DF;border-color:#E3D1A5}.po.jj-po-approved.jj-po-sub:not(.expanded)>.po-head{background:#F7F0DF}.po.jj-po-approved:not(.expanded) .po-quick .pill{background:#F5F9FF;color:#294D77;border-color:#BDD2EC}.po.jj-po-approved.jj-po-sub:not(.expanded) .po-quick .pill{background:#FFFAEF;color:#715820;border-color:#E3D1A5}';document.head.append(style);const page=document.createElement('section');page.id='jj-workpay';page.className='page';document.querySelector('main').append(page);const dialog=document.createElement('dialog');dialog.id='jj-wp-dialog';dialog.className='jj-wp-dialog';document.body.append(dialog);
const action=(name,value,label,cls='btn btn-light')=>`<button class="${cls}" data-wp="${name}" data-value="${E(value)}">${E(label)}</button>`;
function modal(title,html){dialog.innerHTML=`<div class="section-head"><h2>${E(title)}</h2>${action('close','','Close')}</div>${html}`;if(!dialog.open)dialog.showModal();}
function detail(x,w){const linked=w?entries().find(item=>String(item.p.id)===String(w.jobId)&&String(item.po.id)===String(w.po)):null;const c=w?{...w,description:linked?description(linked):w.description}:{job:x.p.name,po:x.po.id,line:getPOBaseTitle(x.po),description:description(x),builderCost:cents(x.po.builderCost),kind:cfg(x).sub?'Sub':'In-house',allocations:alloc(x),status:x.po.status};return `<h3>${E(c.job)} · ${E(c.po)}</h3><b>${E(c.line)}</b><h3>Work description</h3><div class="jj-description">${E(c.description||'No description recorded.')}</div><p>Builder cost: <b>${M(c.builderCost)}</b> · ${E(c.status||'Approved')}${c.completedDate?' · Completed '+E(c.completedDate):''}</p><table><thead><tr><th>${c.kind==='Sub'?'Sub company':'Crew member'}</th><th>Percentage ${c.kind==='Sub'?'of builder cost':'of crew base'}</th><th>Earned</th></tr></thead><tbody>${c.allocations.map(a=>`<tr><td>${E(a.person)}</td><td>${a.pct}%</td><td>${M(a.amount)}</td></tr>`).join('')}</tbody></table>`;}
function end(){return period==='Weekly'?ds(day(start)+6):period==='Bi-weekly'?ds(day(start)+13):period==='Monthly'?ds(Date.UTC(+start.slice(0,4),+start.slice(5,7),0)/86400000):start.slice(0,4)+'-12-31';}
function matches(w){return (!job||w.jobId===job)&&(kind==='Everyone'||w.kind===kind)&&(period==='All time'||w.completedDate>=start&&w.completedDate<=end());}
function select(id,label,values,current){return `<label>${label}<select class="input" data-filter="${id}">${values.map(v=>{const [value,text]=Array.isArray(v)?v:[v,v];return `<option value="${E(value)}" ${current===value?'selected':''}>${E(text)}</option>`}).join('')}</select></label>`;}
function periodUI(){return select('period','Time period',['Weekly','Bi-weekly','Monthly','Yearly','All time'],period)+(period==='All time'?'':period==='Yearly'?select('year','Year',Array.from({length:21},(_,i)=>String(new Date().getFullYear()+1-i)),start.slice(0,4)):period==='Monthly'?`<div>${action('month',-1,'‹')} <b>${E(start.slice(0,7))}</b> ${action('month',1,'›')}</div>`:`<div>${action('calendar','',start+' – '+end())}<div id="jj-calendar"></div></div>`);}
function filters(){return `<div class="toolbar">${select('kind','Team',['Everyone','In-house','Sub'],kind)}${select('job','Job',[['','All jobs'],...state.projects.map(p=>[String(p.id),p.name])],job)}${periodUI()}</div>`;}
function recordsTable(list){return `<div class="table-wrap"><table><thead><tr><th>Job / P.O.</th><th>Payee</th><th>Completed</th><th>%</th><th>Earned</th><th>Paid</th><th>Balance</th><th></th></tr></thead><tbody>${list.map(r=>`<tr><td>${action('work-detail',r.workId,r.w.line+' · '+r.w.job+' · '+r.w.po)}<br>${E(r.w.job)}<br>${E(r.w.line)}</td><td>${E(r.person)}</td><td>${E(r.w.completedDate)}</td><td>${r.pct}%</td><td>${M(r.amount)}</td><td>${M(r.amount-r.balance)}</td><td>${M(r.balance)}</td><td>${r.balance>0?action('pay',JSON.stringify([r.workId,r.person]),'Ready to pay'): 'Paid'}${r.w.kind==='In-house'?action('incomplete',r.workId,'Mark incomplete'):''}${mode==='work'&&canApprovePO()?action('unapprove-edit',r.workId,'Undo Approval / Edit P.O.'):''}</td></tr>`).join('')||'<tr><td colspan="8">No completed work in this period.</td></tr>'}</tbody></table></div>`;}
function render(){if(!doc){page.innerHTML='<h2>Work & Pay</h2><p>Connect to payment storage to continue.</p>'+action('refresh','','Connect / Refresh');return;}
 page.innerHTML=`<div class="page-title"><h2>${mode==='subs'?'Subs Summary':mode==='inhouse'?'In-house Summary':'Payments'}</h2>${action('refresh','','Refresh')}${action('export','','Export payment backup')}</div><div class="toolbar">${action('mode','work','Work & pay')}${action('mode','history','Payment history')}${action('mode','subs','Subs Summary')}${action('mode','inhouse','In-house Summary')}</div>`;
 if(mode==='history'){renderHistory();return;}
 if(mode==='subs'){const scopes=entries().filter(x=>cfg(x).sub&&(!job||String(x.p.id)===job));page.innerHTML+=select('job','Job',[['','All jobs'],...state.projects.map(p=>[String(p.id),p.name])],job)+action('print-subs','','Print all subs')+action('pay-subs','','Record payment for selected ('+subSelected.size+')')+'<p>Select completed P.O.s for one sub company to record one combined payment, or use Record payment on an individual line.</p>';const companies=new Set(scopes.map(x=>cfg(x).company));for(const company of companies){page.innerHTML+=`<div class="section-head"><h3>${E(doc.companies[company]?.name||'Unassigned sub')}</h3>${action('print-sub',company??'','Print this sub')}</div>`;const group=scopes.filter(x=>cfg(x).company===company);for(const id of new Set(group.map(x=>String(x.p.id)))){const lines=group.filter(x=>String(x.p.id)===id);page.innerHTML+=`<h4>${E(lines[0].p.name)}</h4><table><tr><th>Select</th><th>P.O. / Work</th><th>Builder cost</th><th>Sub %</th><th>Payout</th><th>Paid / Owed</th><th></th></tr>${lines.map(x=>{const r=rows().find(r=>r.workId===x.key),ready=r&&r.balance>0;return `<tr><td><input type="checkbox" data-sub-select value="${E(x.key)}" aria-label="Select ${E(x.po.id)} for payment" ${subSelected.has(x.key)?'checked':''} ${ready?'':'disabled'}></td><td>${action('po-detail',x.key,getPOBaseTitle(x.po)+' · '+x.p.name+' · '+x.po.id)} ${E(getPOBaseTitle(x.po))}</td><td>${money(x.po.builderCost)}</td><td>${cfg(x).subPct}%</td><td>${M(alloc(x)[0].amount)}</td><td>${r?M(r.amount-r.balance)+' paid / '+M(r.balance)+' owed':'Not complete'}</td><td>${ready?action('pay',JSON.stringify([x.key,r.person]),'Record payment'):r?'Paid':x.po.status==='Approved'?action('complete',x.key,'Work complete'):'Awaiting approval'}</td></tr>`;}).join('')}<tr><td colspan="4">Job total</td><td>${M(lines.reduce((s,x)=>s+alloc(x)[0].amount,0))}</td></tr></table>`;}}return;}
 if(mode==='inhouse')kind='In-house';page.innerHTML+=filters();const list=rows().filter(r=>matches(r.w));
 if(mode==='inhouse'){const people=[...new Set([...names,...list.map(r=>r.person)])];page.innerHTML+=`<table><tr><th>Employee</th><th>Earned in selected period</th></tr>${people.map(n=>`<tr><td>${E(n)}</td><td>${M(list.filter(r=>r.person===n).reduce((s,r)=>s+r.amount,0))}</td></tr>`).join('')}</table>`;if(!people.includes(person))person=people[0];page.innerHTML+=select('person','Employee',people,person)+action('print-employee','','Print employee breakdown')+recordsTable(list.filter(r=>r.person===person));return;}
 page.innerHTML+=recordsTable(list);const pending=entries().filter(x=>x.po.status==='Approved'&&(!doc.work[x.key]||incomplete(x.key))&&(!job||String(x.p.id)===job)&&(kind==='Everyone'||(cfg(x).sub?'Sub':'In-house')===kind));page.innerHTML+=`<h3>Approved work awaiting completion</h3><p>Older P.O.s are not marked complete automatically. Choose the actual completion date.</p><table>${pending.map(x=>`<tr><td>${action('po-detail',x.key,getPOBaseTitle(x.po)+' · '+x.p.name+' · '+x.po.id)}<br>${E(x.p.name)} · ${E(getPOBaseTitle(x.po))}</td><td>${action('complete',x.key,'Work complete')}${canApprovePO()?action('unapprove-edit',x.key,'Undo Approval / Edit P.O.'):''}</td></tr>`).join('')}</table>`;}
async function open(m){mode=m;go('jj-workpay');page.classList.add('active');try{await load();}catch(e){err(e);}render();}
function printContent(title,html){modal(title,html+`<p>${action('print','','Print copy')}</p>`);}
function statement(list){return `<p>${period==='All time'?'All time':E(start+' – '+end())} · Approved completed earnings, not a payment receipt.</p><table><tr><th>Job / P.O.</th><th>Work / Description</th><th>Completed</th><th>%</th><th>Earned</th></tr>${list.map(r=>`<tr><td>${E(r.w.job)}<br>${E(r.w.po)}</td><td><b>${E(r.w.line)}</b><div class="jj-description">${E(r.w.description||'No description recorded.')}</div></td><td>${E(r.w.completedDate)}</td><td>${r.pct}%</td><td>${M(r.amount)}</td></tr>`).join('')}</table><h3>Total: ${M(list.reduce((s,r)=>s+r.amount,0))}</h3>`;}
function paymentWork(p,l){if(p.voided){const archived=Object.values(doc.workArchive||{}).filter(a=>a.sourceKey===l.workId).sort((a,b)=>b.archivedAt.localeCompare(a.archivedAt))[0];if(archived)return archived.work;}return doc.work[l.workId];}
function renderHistory(){const payments=Object.values(doc.payments),people=[...new Set(payments.map(p=>p.person))];page.innerHTML+=`<div class="toolbar">${select('person','Payee',[['','All payees'],...people],person)}${select('job','Job',[['','All jobs'],...state.projects.map(p=>[String(p.id),p.name])],job)}${select('historyStatus','Status',['All','Recorded','Voided'],historyStatus)}${select('historyMethod','Method',['All','Check','Bank transfer','Cash','Other'],historyMethod)}<label>From date<input class="input" data-filter="historyFrom" value="${E(historyFrom)}" placeholder="YYYY-MM-DD"></label><label>To date<input class="input" data-filter="historyTo" value="${E(historyTo)}" placeholder="YYYY-MM-DD"></label><label>Search P.O. or reference<input class="input" data-filter="query" value="${E(query)}"></label></div>`;if((historyFrom&&!validDate(historyFrom))||(historyTo&&!validDate(historyTo))||(historyFrom&&historyTo&&historyFrom>historyTo)){page.innerHTML+='<p>Enter a valid date range.</p>';return;}const filtered=payments.filter(p=>(!person||p.person===person)&&(!job||p.lines.some(l=>paymentWork(p,l)?.jobId===job))&&(historyStatus==='All'||(p.voided?'Voided':'Recorded')===historyStatus)&&(historyMethod==='All'||p.method===historyMethod)&&(!historyFrom||p.date>=historyFrom)&&(!historyTo||p.date<=historyTo)&&JSON.stringify(p).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));page.innerHTML+=`<table><tr><th>Date / Payday</th><th>Payee</th><th>Method / Reference</th><th>Amount</th><th>Status</th><th></th></tr>${filtered.map(p=>`<tr><td>${E(p.date)}<br>${E(p.payday)}</td><td>${E(p.person)}</td><td>${E(p.method)}<br>${E(p.reference)}</td><td>${M(p.lines.reduce((s,l)=>s+l.amount,0))}</td><td>${p.voided?'Voided':'Recorded'}</td><td>${action('payment-detail',p.id,'View details')}</td></tr>`).join('')}</table>`;}
function paymentForm(workId,name){const list=rows().filter(r=>r.person===name&&r.balance>0),anchor=day('2026-09-11'),nearest=anchor+Math.ceil((day(today())-anchor)/14)*14;modal('Record payment · '+name,`<form data-form="payment"><p>This records a payment already made. It does not send money.</p><label>Bi-weekly payday<select class="input" name="payday">${Array.from({length:53},(_,i)=>ds(nearest+(i-26)*14)).map(s=>`<option ${s===ds(nearest)?'selected':''}>${s}</option>`).join('')}</select></label><label>Payment date<input class="input" name="date" value="${today()}" required placeholder="YYYY-MM-DD"></label><label>Method<select class="input" name="method"><option>Check</option><option>Bank transfer</option><option>Cash</option><option>Other</option></select></label><label>Reference<input class="input" name="reference" maxlength="150"></label><label>Notes<textarea class="input" name="note" maxlength="2000"></textarea></label><table><tr><th>Include</th><th>Job / P.O.</th><th>Owed</th><th>Pay amount</th></tr>${list.map(r=>`<tr><td><input type="checkbox" name="include" value="${E(r.workId)}" ${(Array.isArray(workId)?workId.includes(r.workId):r.workId===workId)?'checked':''}></td><td>${E(r.w.line)}<br>${E(r.w.job)} · ${E(r.w.po)}</td><td>${M(r.balance)}</td><td><input type="number" step="0.01" min="0.01" max="${r.balance/100}" value="${r.balance/100}" data-amount="${E(r.workId)}"></td></tr>`).join('')}</table><input type="hidden" name="person" value="${E(name)}"><h3 id="jj-payment-total"></h3><button class="btn btn-gold">Save payment record</button></form>`);updatePaymentTotal();}
function updatePaymentTotal(){const form=dialog.querySelector('[data-form="payment"]');if(!form)return;let total=0;for(const box of form.querySelectorAll('[name="include"]:checked')){const input=[...form.querySelectorAll('[data-amount]')].find(n=>n.dataset.amount===box.value);total+=cents(input?.value);}const label=document.getElementById('jj-payment-total');if(label)label.textContent='Total payment: '+M(total);}
document.addEventListener('input',e=>{if(e.target.hasAttribute('data-amount'))updatePaymentTotal();});
document.addEventListener('change',e=>{if(e.target.name==='include')updatePaymentTotal();});
function calendar(month=start.slice(0,7)){const y=+month.slice(0,4),m=+month.slice(5,7),offset=new Date(Date.UTC(y,m-1,1)).getUTCDay(),days=new Date(Date.UTC(y,m,0)).getUTCDate();document.getElementById('jj-calendar').innerHTML=`${action('calendar-month',ds(Date.UTC(y,m-2,1)/86400000).slice(0,7),'‹')} ${E(month)} ${action('calendar-month',ds(Date.UTC(y,m,1)/86400000).slice(0,7),'›')}<div class="jj-calendar">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>'<small>'+d+'</small>').join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const s=month+'-'+String(i+1).padStart(2,'0');return `<button data-wp="date" data-value="${s}" ${(offset+i)%7?'disabled':''}>${i+1}</button>`}).join('')}</div>`;}
function lockedNumbers(x){const w=doc?.work[x.key],c=cfg(x),list=w?.allocations||alloc(x);return `<table style="width:100%"><thead><tr><th>${(w?.kind==='Sub'||c.sub)?'Sub company':'Crew member'}</th><th>Percentage</th><th>Base pay</th></tr></thead><tbody>${list.map(a=>`<tr><td>${E(a.person)}</td><td>${a.pct}%</td><td>${M(a.amount)}</td></tr>`).join('')||'<tr><td colspan="3">Unassigned</td></tr>'}</tbody></table>`;}
function controls(x){const c=cfg(x),locked=x.po.status==='Approved'||!!doc?.work[x.key];return `<div class="jj-work-controls" data-key="${E(x.key)}"><label><input type="checkbox" data-config="sub" ${c.sub?'checked':''} ${locked?'disabled':''}> Sub</label>${locked?'<div class="note">Locked · Undo Approval to edit this P.O.</div>'+lockedNumbers(x):c.sub?`<label>Sub company<select class="input" data-config="company"><option value="">Choose sub</option>${Object.entries(doc?.companies||{}).map(([id,s])=>`<option value="${E(id)}" ${id===c.company?'selected':''}>${E(s.name)}</option>`).join('')}</select></label>${action('company-new',x.key,'+ Add sub')}${c.company?action('company-edit',c.company,'Edit company name'):''}<label>Percentage of builder cost<input class="input" type="number" min="0" max="100" step="0.01" value="${c.subPct}" data-config="subPct"></label><p>Sub payout: <b>${M(alloc(x)[0].amount)}</b></p>`:`<div class="split-grid"><b>Crew member</b><b>Split %</b><b>Base pay</b>${c.splits.map((s,i)=>`<select class="input" data-crew="${i}" data-field="name"><option value="">Select employee…</option>${[...new Set([...names,...c.splits.map(a=>a.name).filter(Boolean)])].map(n=>`<option ${s.name===n?'selected':''}>${E(n)}</option>`).join('')}</select><input class="input" type="number" min="0" max="100" step="0.01" value="${s.pct}" data-crew="${i}" data-field="pct"><span>${money(x.po.builderCost*.6*Number(s.pct)/100)}</span>`).join('')}</div><p>${c.splits.length<4?action('crew-add',x.key,'+ Add crew member'):''} ${c.splits.length>1?action('crew-remove',x.key,'Remove last member'):''}</p>`}</div>`;}
const originalRenderPO=renderPO;
renderPO=function(po,i){const x={p:selectedProject(),po,key:key(selectedProject(),po)};const config=cfg(x),displayPO={...po,splits:config.sub?[{name:doc?.companies[config.company]?.name||'',pct:100}]:config.splits};let html=originalRenderPO(displayPO,i);const snapshot=doc?.work[x.key];const ownerNames=snapshot?snapshot.allocations.map(a=>a.person):config.sub?[doc?.companies?.[config.company]?.name||(config.company?'Connect Work & Pay to load company':'Unassigned')]:config.splits.filter(s=>s.name&&Number(s.pct)>0).map(s=>s.name);const ownerLabel=(snapshot?.kind==='Sub'||(!snapshot&&config.sub)?'Sub: ':'Crew: ')+([...new Set(ownerNames)].join(' · ')||'Unassigned');html=html.replace('</h4>','</h4><div class="jj-po-owner">'+E(ownerLabel)+'</div>');if(po.status==='Approved')html=html.replace('class="card po ', 'class="card po jj-po-approved ');if((snapshot?.kind|| (config.sub?'Sub':'In-house'))==='Sub')html=html.replace('class="card po ', 'class="card po jj-po-sub ');if(config.sub){html=html.replace(/<div class="alloc-grid">[\s\S]*?<div class="section-head"/,`<div class="alloc-grid"><div class="alloc"><span>Sub · ${config.subPct}% of builder cost</span><b>${M(alloc(x)[0].amount)}</b></div></div><div class="section-head"`).replace(money(po.builderCost*.6)+'</b> base',M(alloc(x)[0].amount)+'</b> sub payout');}const completed=doc?.work[x.key];if(completed){html=html.replace(/<div class="split-grid"[\s\S]*?<div class="approval-trail">/, '<div class="approval-trail">');}else if(doc||po.status==='Approved'){html=html.replace(/<div class="split-grid"[\s\S]*?<div class="approval-trail">/,'<div class="approval-trail">');}return html.replace('<div class="approval-trail">',((doc||po.status==='Approved')?controls(x):'<p>'+action('connect','','Connect Work & Pay')+'</p>')+'<div class="approval-trail">');};
const originalBuildNav=buildNav;buildNav=function(){originalBuildNav();topNav.insertAdjacentHTML('beforeend',`<button data-wp="open" data-value="work"><span class="nav-icon">$</span><span>Payments</span></button>`);};
const originalRenderAll=renderAll;renderAll=function(){originalRenderAll();if(doc&&page.classList.contains('active')&&!dialog.open)render();};
const originalRenderHub=renderPayByLine;renderPayByLine=function(){originalRenderHub();const nav=document.querySelector('#paybyline .po-hub-nav');if(nav)nav.insertAdjacentHTML('beforeend',action('open','subs','Subs Summary')+action('open','inhouse','In-house Summary'));};
function lockedSelected(){return selectedPOs().some(po=>doc?.work[key(selectedProject(),po)]);}
for(const name of ['updateSplit','confirmDeletePO']){const orig=window[name];window[name]=function(i,...args){if(!doc)return alert('Connect Work & Pay before editing P.O.s.');if(doc?.work[key(selectedProject(),selectedProject().pos[i])]||(name==='updateSplit'&&selectedProject().pos[i]?.status==='Approved')){alert('This P.O. has completed work recorded. Its original split and payment history are protected.');return;}return orig(i,...args);};}
undoPOApproval=async function(i){const p=selectedProject(),po=p.pos[i];if(po)return undoWorkApproval(key(p,po));};
async function undoWorkApproval(k){if(busy)return false;if(!canApprovePO())return alert('Approval permission required.');if(!doc){try{await load();}catch(e){return err(e);}}const x=entry(k);if(!x||x.po.status!=='Approved')return false;const {p,po}=x;const stamp=new Date().toISOString(),reason='Approval undone for '+po.id;
 const ok=await change(d=>{
  for(const payment of Object.values(d.payments)){if(payment.voided||!payment.lines.some(l=>l.workId===k))continue;const remaining=payment.lines.filter(l=>l.workId!==k);payment.voided=true;payment.voidReason=reason;payment.voidedAt=stamp;payment.voidedBy=state.currentUser;
   if(remaining.length){const replacement=clone(payment),id=crypto.randomUUID();delete replacement.voidReason;delete replacement.voidedAt;delete replacement.voidedBy;Object.assign(replacement,{id,voided:false,lines:remaining,createdAt:stamp,replacesPaymentId:payment.id,note:(payment.note||'')+' · Remaining allocations retained after '+reason});d.payments[id]=replacement;}
  }
  if(d.work[k]){d.workArchive=d.workArchive||{};d.workArchive[crypto.randomUUID()]={sourceKey:k,work:clone(d.work[k]),lifecycle:clone(d.lifecycle?.[k]||{}),archivedAt:stamp,archivedBy:state.currentUser,reason};delete d.work[k];if(d.lifecycle)delete d.lifecycle[k];}
 });if(!ok)return;po.status='Draft';po.approvedBy='';po.preApprovedBy='';delete po.approvedDate;subSelected.delete(k);saveState(false);renderAll();toast('Approval removed. Linked payment allocations voided; history retained.');return true;}
const originalPOPrint=poPrintHTML;poPrintHTML=function(p,po,i,breakPage=false){const x={p,po,key:key(p,po)};if(doc)return '<section class="print-section '+(breakPage?'print-page-break':'')+'">'+detail(x,doc.work[x.key])+'</section>';return originalPOPrint(p,po,i,breakPage);};
const oldBulk=applyBulkSplit;applyBulkSplit=function(n){if(!doc)return alert('Connect Work & Pay before editing P.O.s.');if(lockedSelected()||selectedPOs().some(po=>po.status==='Approved'))return alert('Undo approval before changing these P.O. splits.');if(doc&&selectedPOs().some(po=>doc.configs[key(selectedProject(),po)]))return alert('Edit these crew splits on their individual P.O.s.');return oldBulk(n);};
const oldDelete=confirmBulkDelete;confirmBulkDelete=function(){if(!doc)return alert('Connect Work & Pay before deleting P.O.s.');if(lockedSelected())return alert('Completed P.O.s cannot be deleted.');return oldDelete();};
function validAlloc(x){const c=cfg(x),a=alloc(x),total=c.sub?Number(c.subPct):(c.splits||[]).reduce((s,v)=>s+Number(v.pct||0),0);return Number.isFinite(total)&&total>0&&total<=100&&a.length>0&&a.every(v=>Number.isSafeInteger(v.amount)&&v.amount>0)&&(c.sub?!!doc.companies[c.company]:c.splits.every(v=>!Number(v.pct)||!!v.name))&&new Set(a.map(v=>v.person)).size===a.length;}
const oldStatus=setPOStatus;setPOStatus=function(i,status){if(!doc)return alert('Connect Work & Pay before approving P.O.s.');const x={p:selectedProject(),po:selectedProject().pos[i]};x.key=key(x.p,x.po);if(status==='Approved'&&doc&&!validAlloc(x))return alert('Choose the payee(s) and a valid percentage before approval.');if(doc&&status==='Approved'){if(!canApprovePO())return alert('You do not have approval permission.');x.po.status='Approved';x.po.approvedBy=state.currentUser;x.po.approvedDate=today();saveState(false);renderAll();return;}return oldStatus(i,status);};
bulkApprove=function(){if(!doc)return alert('Connect Work & Pay first.');if(!canApprovePO())return alert('Approval permission required.');let n=0;for(const po of selectedPOs()){const x={p:selectedProject(),po,key:key(selectedProject(),po)};if(!doc.work[x.key]&&validAlloc(x)){po.status='Approved';po.approvedBy=state.currentUser;po.approvedDate=today();n++;}}saveState(false);renderAll();toast(n+' P.O.s approved');};
printSinglePO=function(i){const p=selectedProject(),po=p.pos[i];if(!doc)return alert('Connect Work & Pay before printing payout details.');const x={p,po,key:key(p,po)};printContent('J&J · P.O. '+po.id,detail(x,doc.work[x.key]));};
printAllPOs=function(){if(!doc)return alert('Connect Work & Pay before printing payout details.');const p=selectedProject();printContent('J&J · '+p.name+' · P.O.s',p.pos.map(po=>{const x={p,po,key:key(p,po)};return detail(x,doc.work[x.key]);}).join('<hr>'));};
document.addEventListener('change',async event=>{const t=event.target;if(t.hasAttribute('data-sub-select')){t.checked?subSelected.add(t.value):subSelected.delete(t.value);render();return;}if(t.dataset.filter){const v=t.value;switch(t.dataset.filter){case 'kind':kind=v;break;case 'job':job=v;break;case 'person':person=v;break;case 'period':period=v;start=period==='Monthly'?start.slice(0,7)+'-01':period==='Yearly'?start.slice(0,4)+'-01-01':ds(day(start)-new Date(start+'T00:00:00Z').getUTCDay());break;case 'year':start=v+'-01-01';break;case 'historyStatus':historyStatus=v;break;case 'historyMethod':historyMethod=v;break;case 'historyFrom':historyFrom=v;break;case 'historyTo':historyTo=v;break;case 'query':query=v;}render();return;}const container=t.closest('[data-key]');if(!container||(!t.dataset.config&&!t.hasAttribute('data-crew')))return;const x=entry(container.dataset.key);if(!x||doc.work[x.key])return;const c=clone(cfg(x));if(t.dataset.config){c[t.dataset.config]=t.dataset.config==='sub'?t.checked:t.dataset.config==='subPct'?Number(t.value):t.value;if(!Number.isFinite(c.subPct)||c.subPct<0||c.subPct>100)return err(Error('Use a percentage from 0 to 100.'));}else{const s=c.splits[Number(t.dataset.crew)];s[t.dataset.field]=t.dataset.field==='pct'?Number(t.value):t.value;if(c.splits.some(v=>!Number.isFinite(Number(v.pct))||v.pct<0||v.pct>100))return err(Error('Use percentages from 0 to 100.'));}if(x.po.status==='Approved')return err(Error('Undo approval before changing this split.'));await change(d=>{d.configs[x.key]=c;});});
document.addEventListener('click',async event=>{const b=event.target.closest('[data-wp]');if(!b)return;const a=b.dataset.wp,v=b.dataset.value;try{
 if(a==='export'){await load();const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),revision,document:doc},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='JJ-Work-Pay-'+today()+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}if(a==='close')return dialog.close();if(a==='print'){document.body.classList.add('jj-print');window.print();return;}if(a==='open')return open(v);if(a==='mode'){mode=v;person='';kind='Everyone';render();return;}if(a==='connect'){await load();renderPayByLine();return;}if(a==='refresh'){await load();render();renderPayByLine();return;}
 if(a==='po-detail'){const x=entry(v);if(x)modal('P.O. details',detail(x,effectiveWork(v)));return;}if(a==='work-detail'){if(doc.work[v])modal('P.O. details',detail(null,effectiveWork(v)));return;}
 if(a==='calendar'||a==='calendar-month')return calendar(v||undefined);if(a==='date'){if(new Date(v+'T00:00:00Z').getUTCDay()!==0)return;start=v;render();return;}if(a==='month'){start=ds(Date.UTC(+start.slice(0,4),+start.slice(5,7)-1+Number(v),1)/86400000);render();return;}
 if(a==='print-employee'){printContent('J&J · '+person+' · Work & Earnings',statement(rows().filter(r=>r.person===person&&r.w.kind==='In-house'&&matches(r.w))));return;}
 if(a==='print-subs'||a==='print-sub'){const scopes=entries().filter(x=>cfg(x).sub&&(!job||String(x.p.id)===job)&&(a==='print-subs'||String(cfg(x).company??'')===v));if(!scopes.length)return err(Error('No subcontractor lines match the selected job.'));let html='<p>Assigned scope · Not a confirmation of payment.</p>';for(const company of new Set(scopes.map(x=>cfg(x).company))){html+=`<h2>${E(doc.companies[company]?.name||'Unassigned sub')}</h2>`;const items=scopes.filter(x=>cfg(x).company===company);for(const jobId of new Set(items.map(x=>x.p.id))){const lines=items.filter(x=>x.p.id===jobId);html+=`<h3>${E(lines[0].p.name)}</h3><table><tr><th>P.O. / Description</th><th>Builder cost</th><th>Sub %</th><th>Payout</th></tr>${lines.map(x=>`<tr><td>${E(x.po.id)} · ${E(getPOBaseTitle(x.po))}<div class="jj-description">${E(description(x)||'No description recorded.')}</div></td><td>${money(x.po.builderCost)}</td><td>${cfg(x).subPct}%</td><td>${M(alloc(x)[0].amount)}</td></tr>`).join('')}</table><h3>Builder cost total: ${M(lines.reduce((s,x)=>s+cents(x.po.builderCost),0))}</h3><h3>Sub payout total: ${M(lines.reduce((s,x)=>s+alloc(x)[0].amount,0))}</h3>`;}if(new Set(items.map(x=>x.p.id)).size>1)html+=`<h3>All jobs · Builder cost total: ${M(items.reduce((s,x)=>s+cents(x.po.builderCost),0))}</h3><h3>All jobs · Sub payout total: ${M(items.reduce((s,x)=>s+alloc(x)[0].amount,0))}</h3>`;}printContent('J&J · Subcontractor Scope & Pay'+(a==='print-sub'?' · '+E(doc.companies[v]?.name||'Unassigned sub'):''),html);return;}
 if(a==='crew-add'||a==='crew-remove'){const x=entry(v);if(!x||doc.work[v]||x.po.status==='Approved')return err(Error('Undo approval before editing crew.'));const c=clone(cfg(x)),n=c.splits.length+(a==='crew-add'?1:-1);if(n<1||n>4)return;const pct=Math.floor(10000/n);c.splits=Array.from({length:n},(_,i)=>({name:c.splits[i]?.name||'',pct:(pct+(i===n-1?10000-pct*n:0))/100}));await change(d=>{d.configs[v]=c;});return;}
 if(a==='company-new'||a==='company-edit'){const name=prompt('Sub company name',a==='company-edit'?doc.companies[v]?.name||'':'');if(!name?.trim())return;const id=a==='company-edit'?v:crypto.randomUUID();await change(d=>{d.companies[id]={name:name.trim()};if(a==='company-new'){const x=entry(v);if(x&&!d.work[v])d.configs[v]={...clone(cfg(x)),company:id};}});return;}
 if(a==='unapprove-edit'){const x=entry(v);if(x&&await undoWorkApproval(v)){openProjectPOHub(x.p.id,'splits');openPOIds.add(x.po.id);renderPayByLine();}return;}
 if(a==='incomplete'){const w=doc.work[v];if(!w)return;if(w.allocations.some(a=>paid(v,a.person)>0))return err(Error('Void the recorded payment first before marking this P.O. incomplete.'));if(await change(d=>{d.lifecycle=d.lifecycle||{};const prior=d.lifecycle[v]||{history:[]};d.lifecycle[v]={...prior,incomplete:true,history:[...(prior.history||[]),{action:'incomplete',at:new Date().toISOString(),by:state.currentUser}]};})){mode='work';kind='In-house';job='';render();}return;}
 if(a==='pay-subs'){const selected=rows().filter(r=>r.w.kind==='Sub'&&r.balance>0&&subSelected.has(r.workId));if(!selected.length)return err(Error('Select completed P.O.s with an outstanding balance.'));if(new Set(selected.map(r=>r.companyId||r.person)).size!==1)return err(Error('Choose P.O.s for one sub company per payment.'));paymentForm(selected.map(r=>r.workId),selected[0].person);return;}
 if(a==='complete'){const x=entry(v);if(!x||x.po.status!=='Approved')return;if(!validAlloc(x))return err(Error('This P.O. needs named payees and valid percentages.'));modal('Mark work complete',`<form data-form="complete" data-key="${E(v)}">${detail(x)}<fieldset style="margin:18px 0;padding:14px;border:1px solid var(--line);border-radius:10px"><legend>Completed date</legend><p>Choose the date this work was finished. It will appear on summaries and printed breakdowns.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><label>Month<select class="input" name="completedMonth">${Array.from({length:12},(_,i)=>`<option value="${String(i+1).padStart(2,'0')}" ${i+1===Number(today().slice(5,7))?'selected':''}>${new Date(2000,i,1).toLocaleString('en-US',{month:'long'})}</option>`).join('')}</select></label><label>Day<input class="input" name="completedDay" type="number" min="1" max="31" value="${Number(today().slice(8,10))}" required style="width:90px"></label><label>Year<input class="input" name="completedYear" type="number" min="1900" max="9999" value="${today().slice(0,4)}" required style="width:110px"></label></div></fieldset><button class="btn btn-gold">Confirm work complete</button></form>`);return;}
 if(a==='pay'){const [id,n]=JSON.parse(v);paymentForm(id,n);return;}
 if(a==='payment-detail'){const p=doc.payments[v];modal('Payment record',`<p>${E(p.person)} · ${E(p.date)} · Payday ${E(p.payday)} · ${E(p.method)}</p><p>Reference: ${E(p.reference||'—')}</p><p>${E(p.note)}</p>${p.lines.map(l=>`<p>${E(paymentWork(p,l)?.line)} · ${E(paymentWork(p,l)?.job)} · ${E(paymentWork(p,l)?.po)}: ${M(l.amount)}</p>`).join('')}${p.voided?'<p>Voided: '+E(p.voidReason)+'</p>':action('void',v,'Void recorded payment')}`);return;}
 if(a==='void'){const reason=prompt('Reason for voiding this record (does not reverse a bank payment):');if(!reason?.trim())return;if(await change(d=>{const p=d.payments[v];if(!p||p.voided)throw Error('Record already changed.');p.voided=true;p.voidReason=reason.trim();p.voidedAt=new Date().toISOString();p.voidedBy=state.currentUser;}))dialog.close();return;}
 }catch(e){err(e);}});
document.addEventListener('submit',async event=>{const form=event.target;if(!form.dataset.form)return;event.preventDefault();const date=form.dataset.form==='complete'?String(form.elements.completedYear.value).padStart(4,'0')+'-'+form.elements.completedMonth.value+'-'+String(form.elements.completedDay.value).padStart(2,'0'):form.elements.date.value;if(!validDate(date))return err(Error('Enter a valid date as YYYY-MM-DD.'));if(form.dataset.form==='complete'){const x=entry(form.dataset.key);if(!x||x.po.status!=='Approved'||!validAlloc(x))return err(Error('P.O. approval or payees changed. Refresh before continuing.'));if(await change(d=>{if(d.work[x.key]){if(!incomplete(x.key))throw Error('Work is already complete.');const prior=d.lifecycle[x.key];d.lifecycle[x.key]={...prior,incomplete:false,completedDate:date,history:[...(prior.history||[]),{action:'complete',completedDate:date,at:new Date().toISOString(),by:state.currentUser}]};return;}d.work[x.key]={jobId:String(x.p.id),job:x.p.name,po:String(x.po.id),line:getPOBaseTitle(x.po),description:description(x),builderCost:cents(x.po.builderCost),kind:cfg(x).sub?'Sub':'In-house',completedDate:date,status:'Approved',allocations:alloc(x),recordedAt:new Date().toISOString(),recordedBy:state.currentUser};}))dialog.close();return;}
 if(form.dataset.form==='payment'){const name=form.elements.person.value,payday=form.elements.payday.value;if(!validDate(payday)||(day(payday)-day('2026-09-11'))%14!==0)return err(Error('Choose a valid bi-weekly payday.'));const lines=[...form.querySelectorAll('[name=include]:checked')].map(t=>({workId:t.value,person:name,amount:cents([...form.querySelectorAll('[data-amount]')].find(n=>n.dataset.amount===t.value).value)}));if(!lines.length)return err(Error('Select at least one P.O.'));const id=crypto.randomUUID();if(await change(d=>{for(const l of lines){const r=rows().find(r=>r.workId===l.workId&&r.person===name);if(!r||!Number.isSafeInteger(l.amount)||l.amount<=0||l.amount>r.balance)throw Error('Enter amounts within the outstanding balance.');}d.payments[id]={id,person:name,date,payday,method:form.elements.method.value,reference:form.elements.reference.value.trim(),note:form.elements.note.value.trim(),lines,createdAt:new Date().toISOString(),recordedBy:state.currentUser,voided:false};})){dialog.close();mode='history';render();}}
});
window.addEventListener('afterprint',()=>document.body.classList.remove('jj-print'));
buildNav();renderPayByLine();
})();
